//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arsiv.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class İslem
    {
        public int ID { get; set; }
        public Nullable<int> Uye_id { get; set; }
        public Nullable<int> Kitap_id { get; set; }
        public Nullable<System.DateTime> atarih { get; set; }
        public Nullable<System.DateTime> vtarih { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
